language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
    - travis_retry composer install --no-interaction
    - composer info -i

script: 
  - phpunit
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; ./vendor/bin/phpcs -n --standard=PSR2 ./src ./tests ; fi

notifications:
  email: true
